// Lazy-loads the Pagefind UI bundle (emitted to /pagefind by the build) the first
// time the user invokes search. No JS cost until then.
//
// Pagefind's Default UI (pagefind-ui.js) is shipped as a classic IIFE that attaches
// `PagefindUI` to `window` — it is NOT an ES module with a `PagefindUI` export (that
// was the pre-1.5 shape). So we load it via a <script> tag and read the global, rather
// than `await import()` (which returns a namespace without PagefindUI).
let loaded = false;
let loading: Promise<boolean> | null = null;

function loadPagefindUI(): Promise<boolean> {
  if (loading) return loading;
  loading = new Promise<boolean>((resolve) => {
    // The bundle is generated by `pagefind --site dist` AFTER the build, so it does
    // not exist on the dev server — onerror lets search no-op there.
    const s = document.createElement('script');
    s.src = '/pagefind/pagefind-ui.js';
    s.onload = () => resolve(true);
    s.onerror = () => { loading = null; resolve(false); }; // allow a later retry
    document.head.appendChild(s);
  });
  return loading;
}

async function openSearch() {
  const host = document.getElementById('search-modal');
  if (!host) return;
  if (loaded) {
    host.hidden = false;
    host.querySelector<HTMLInputElement>('.pagefind-ui__search-input')?.focus();
    return;
  }
  const ok = await loadPagefindUI();
  const PagefindUI = (window as unknown as { PagefindUI?: new (opts: Record<string, unknown>) => unknown }).PagefindUI;
  if (!ok || !PagefindUI) return; // no index available (e.g. the dev server)
  loaded = true;
  host.hidden = false;
  new PagefindUI({ element: '#search-modal .inner', showSubResults: true });
  host.querySelector<HTMLInputElement>('.pagefind-ui__search-input')?.focus();
}

export function initSearch() {
  const btn = document.getElementById('nav-search');
  btn?.addEventListener('click', openSearch);
  // First keyboard focus (tabbing to the button) also loads search — matches the
  // spec's "loads on first focus". One-shot; openSearch is idempotent via `loaded`.
  btn?.addEventListener('focus', openSearch, { once: true });
  document.getElementById('search-close')?.addEventListener('click', () => {
    const host = document.getElementById('search-modal');
    if (host) host.hidden = true;
  });
}
document.addEventListener('DOMContentLoaded', initSearch);
