// Lazy-loads the Pagefind UI bundle (emitted to /pagefind by the build) the first
// time the user invokes search. No JS cost until then.
let loaded = false;
async function openSearch() {
  if (loaded) { document.querySelector<HTMLInputElement>('.pagefind-ui__search-input')?.focus(); return; }
  loaded = true;
  // Pagefind's UI bundle is generated by `pagefind --site dist` AFTER the build,
  // so it does not exist during dev or at compile time. Passing the path as a
  // runtime VARIABLE (not a string literal) keeps Vite/Rollup from trying to
  // resolve it in either dev or build; @vite-ignore silences the analysis warning.
  const pagefindUiSrc = '/pagefind/pagefind-ui.js';
  let mod: { PagefindUI: new (opts: Record<string, unknown>) => unknown };
  try {
    mod = await import(/* @vite-ignore */ pagefindUiSrc);
  } catch {
    // No index available (e.g. the dev server, which never runs Pagefind).
    loaded = false; // allow a later retry once a real build is served
    return;
  }
  const host = document.getElementById('search-modal')!;
  host.hidden = false;
  new mod.PagefindUI({ element: '#search-modal .inner', showSubResults: true });
  host.querySelector<HTMLInputElement>('.pagefind-ui__search-input')?.focus();
}
export function initSearch() {
  const btn = document.getElementById('nav-search');
  btn?.addEventListener('click', openSearch);
  // First keyboard focus (tabbing to the button) also loads search — matches the
  // spec's "loads on first focus". One-shot; openSearch is idempotent via `loaded`.
  btn?.addEventListener('focus', openSearch, { once: true });
  document.getElementById('search-close')?.addEventListener('click', () => {
    document.getElementById('search-modal')!.hidden = true;
  });
}
document.addEventListener('DOMContentLoaded', initSearch);
